version: '3.6'

services:

  api01:
    image: rodolfodpk/rinhadebackend-jvm:latest
    hostname: api01
    ports:
      - "8081:8081"
      - "8082:8081"
    environment:
      - APP_TRANSACOES_HTTP_PORT=8081
      - APP_EXTRATO_HTTP_PORT=8082
      - QUARKUS_BANNER_ENABLED=false
      - QUARKUS_MICROMETER_ENABLED=false
      - QUARKUS_LOG_LEVEL=INFO
    #    healthcheck:
    #      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8081/clientes/1/extrato" ]
    #      interval: 2s
    #      retries: 10
    #    depends_on:
    #      rinhadb:
    #        condition: service_healthy
    #    ulimits:
    #      nofile:
    #        soft: 1000000
    #        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "250MB"

  api02:
    image: rodolfodpk/rinhadebackend-jvm:latest
    hostname: api02
    ports:
      - "8083:8082"
      - "8084:8082"
    environment:
      - APP_TRANSACOES_HTTP_PORT=8083
      - APP_EXTRATO_HTTP_PORT=8084
      - QUARKUS_BANNER_ENABLED=false
      - QUARKUS_MICROMETER_ENABLED=false
      - QUARKUS_LOG_LEVEL=INFO
    #      - HAZELCAST_IP=hazelcast1
    #    healthcheck:
    #      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8082/clientes/1/extrato" ]
    #      interval: 2s
    #      retries: 10
    #    depends_on:
    #      rinhadb:
    #        condition: service_healthy
    #      redis:
    #        condition: service_healthy
    #    ulimits:
    #      nofile:
    #        soft: 1000000
    #        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "250MB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    #      api01:
    #        condition: service_healthy
    #      api02:
    #        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://127.0.0.1:9999/clientes/1/extrato"]
      test: [ "CMD", "sleep", "5" ]
      interval: 3s
      retries: 15
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "40MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1